### ISSUE TITLE
scroll lock

### ISSUE THREAD

**Issue by louvervecken** [thocoo/gamma-desk#1]
A scroll lock in the console would be nice.
I seem to remember it from an earlier version of this software ;-)

**Comment by thocoo** [comment]
Implemented as menu item in console menu > view > Auto Scroll
Added ScrollLock as default shortcut.
Note that QT don't really has the feature to check the state of the scroll lock on the keyboard.
Hitting ScrollLock will toggle the 'auto scroll' state in GD, but it will not necessary match the LED state on the scroll lock key.
