### ISSUE TITLE
histogram is not (yet) supporting (u)int64 causing a crash when it is displayed

### ISSUE THREAD

**Issue by louvervecken** [thocoo/gamma-desk#11]
To replicate:
`gui.show(np.zeros((10, 10), dtype='int64'))`

Might be as easy as including support at line 132 of imgdata.py.

**Comment by thocoo** [comment]
Latest commits about support for 64bit seems to solve the problem

**Comment by florisla** [comment]
Was fixed in dab4d7cd37edf6e43dd30268a9e7a70420ed0b34 .
