### ISSUE TITLE
Parentheses double when selecting with shift key

### ISSUE THREAD

**Issue by louvervecken** [thocoo/gamma-desk#2]
Single parentheses double when selecting text in the console input.
For example when having this text in the console:
test_str = 'hi'

If you put the cursor in the first position, hold shit and press the up or down key then all single parentheses would double.
You get:
test_str = ''hi''

You can do it multiple times:
test_str = ''''''''''''''''hi''''''''''''''''

**Comment by florisla** [comment]
I tend to hold shit all the time when in the lab ;-)

**Comment by thocoo** [comment]
Fixed, I think
