### ISSUE TITLE
Error loading PGM images

### ISSUE THREAD

**Issue by miguelmpn** [thocoo/gamma-desk#23]
Hello,

Loading some image formats, like PGM we get an error in the following line:

[gdesk/panels/imgview/imgview.py](https://github.com/thocoo/gamma-desk/blob/ab23a780b3c41137efa76e17f58cc85e637b2080/gdesk/panels/imgview/imgview.py#LL1364C57-L1364C57)

Because of the following call:

[imageio/imageio/core/format.py](https://github.com/imageio/imageio/blob/b0f9f3bfce914f335d06375c76c094a10dcca236/imageio/core/format.py#L683)

This is because not all image plugins use the attribute _format.
I tried to solve this issue with imageio and they said this code is deprecated and gave a solution instead, can we use it?. https://github.com/imageio/imageio/issues/999#issuecomment-1570545922

**Comment by louvervecken** [comment]
Issue is fixed as proposed in the imageio issue you created, thanks for that.
It will be included in the next release.
