### ISSUE TITLE
Ubuntu 20.04 Support

### ISSUE THREAD

**Issue by denver-lloyd** [thocoo/gamma-desk#31]
Hello,

Does gamma-desk work on Ubuntu? I see there is a `linux_config.json` located here:

https://github.com/thocoo/gamma-desk/tree/main/gdesk/config

But when pip install per the README this file is not present in `/gdesk/confg`. I can manually copy it, but I get several errors. I see the `defaults_linux.json` hasn't been updated in ~2 years, so I just wanted to check:

1.) Do you expect gamma-desk to work out of the box on Linux?
2.) If so is there a reason `defaults_linux.json` isn't installed when installing via pip?

Thanks,
Denver

**Comment by louvervecken** [comment]
Hi Denver,

Good to hear from you.
We do have it running on linux but the default_linux.json file being missing is still something that needs to be fixed. What kind of errors are you getting when you manually add it? On which python and pyside version are you?

Regards,
Lou

**Comment by denver-lloyd** [comment]
Hi Lou,

Good to hear from you as well :) 

It looks like my above issues were user error (running via SSH, so it was a bit of a mess). I ended up just transitioning to mac and noticed there was no system support for Darwin. I added the bare minimum needed to get gamma-desk working on mac and the PR is here:

https://github.com/thocoo/gamma-desk/pull/32

Thanks,
Denver
