### ISSUE TITLE
Plotting crashes on Linux with PySide6

### ISSUE THREAD

**Issue by florisla** [thocoo/gamma-desk#36]
I've been struggling to do `plt.show()` on Rocky Linux 9 (Red Hat RHEL).

The plot shows up, but some seconds later the process crashes with a segmentation fault.

Reverting to older versions of `PySide6` and `matplotlib` makes no difference. Also switching from Wayland to Xorg doesn't help.

Any ideas on what to try next are welcome.

**Comment by louvervecken** [comment]
I think I've only used PySide2 on linux, for this reason.
But it's blocking us from moving higher than python 3.10.

Have you tried plotting with matplotlib using the pyside6 backend outside of desk? This should tell us if it's a pyside/mtpl issue or a desk issue.

**Comment by louvervecken** [comment]
Commenting out this code seems to fix the issue:

```python
            # Adjust the buf reference count to work around a memory
            # leak bug in QImage under PySide on Python 3.
            if QT_API in ('PySide', 'PySide2', 'PySide6'):
                ctypes.c_long.from_address(id(buf)).value = 1
```

@thocoo do you remember where this came from and if it's still needed?

**Comment by florisla** [comment]
I pushed a fix to only fiddle with the refcount on PySide/PySide2.

But I'm not sure there is plotting memory leak at the moment...

This snippet adds ~900 MB to the memory use and it does not seem to get freed after plot close.

    from matplotlib import pyplot as plt; plt.plot(range(16*1024*1024)); plt.show();

**Comment by florisla** [comment]
Thanks, that helps.  No memory leak bug it seems.

I'll consider this issue fixed unless @thocoo has some other feedback.
