### ISSUE TITLE
Help on live function returns help of MarkUpdateRun class

### ISSUE THREAD

**Issue by louvervecken** [thocoo/gamma-desk#7]
When asking for the help of a function in a script file we would expect the docstring of the function. Now the help of the MarkUpdateRun class is returned.
A workaround is calling the help of the '.func' attribute of the function but one needs to know this.

**Comment by thocoo** [comment]
The help functions is just the native Python help. I can not modify the help function.
The problem I have is that the script callable if not a function but a class with a defined __call__.
And the Python wrapper functions seem only to work to wrap functions by functions, not functions by classes.
To solve it, I replaced the MarkUpdateRun class by a enclosed function (markUpdateCall).
The functools wrapper seems to work fine with it.
